name: Backup Repository

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    environment: BackupEnvironment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: backup branch
        id: create_branch
        run: |
          echo "Creating backup branch"
          TIMESTAMP=$(TZ="Europe/Istanbul" date +"%Y-%m-%d-%H-%M")
          BRANCH_NAME="backup-$TIMESTAMP"
          echo "Branch name: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      - name: backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/moanxxx/test_workflou11
          git remote -v  # List remotes to verify
      - name: Pulling changes
        run: |
          echo "Pulling changes from backup repository"
          git pull backup main --rebase || echo "No changes to pull"
      - name: Check PAT permissions
        run: |
          echo "Checking PAT permissions"
          curl -H "Authorization: token ${{ secrets.TARGET_REPO_TOKEN }}" https://api.github.com/user/repos
      - name: Push
        run: |
          echo "Pushing to remote repository"
          git push backup ${{ env.BRANCH_NAME }} --force        
